// +build ignore

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: darknet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "darknet.pb-c.h"
void   darknet__darknet_flow__init
                     (Darknet__DarknetFlow         *message)
{
  static Darknet__DarknetFlow init_value = DARKNET__DARKNET_FLOW__INIT;
  *message = init_value;
}
size_t darknet__darknet_flow__get_packed_size
                     (const Darknet__DarknetFlow *message)
{
  assert(message->base.descriptor == &darknet__darknet_flow__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t darknet__darknet_flow__pack
                     (const Darknet__DarknetFlow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &darknet__darknet_flow__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t darknet__darknet_flow__pack_to_buffer
                     (const Darknet__DarknetFlow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &darknet__darknet_flow__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Darknet__DarknetFlow *
       darknet__darknet_flow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Darknet__DarknetFlow *)
     protobuf_c_message_unpack (&darknet__darknet_flow__descriptor,
                                allocator, len, data);
}
void   darknet__darknet_flow__free_unpacked
                     (Darknet__DarknetFlow *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &darknet__darknet_flow__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   darknet__darknet_flows__init
                     (Darknet__DarknetFlows         *message)
{
  static Darknet__DarknetFlows init_value = DARKNET__DARKNET_FLOWS__INIT;
  *message = init_value;
}
size_t darknet__darknet_flows__get_packed_size
                     (const Darknet__DarknetFlows *message)
{
  assert(message->base.descriptor == &darknet__darknet_flows__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t darknet__darknet_flows__pack
                     (const Darknet__DarknetFlows *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &darknet__darknet_flows__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t darknet__darknet_flows__pack_to_buffer
                     (const Darknet__DarknetFlows *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &darknet__darknet_flows__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Darknet__DarknetFlows *
       darknet__darknet_flows__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Darknet__DarknetFlows *)
     protobuf_c_message_unpack (&darknet__darknet_flows__descriptor,
                                allocator, len, data);
}
void   darknet__darknet_flows__free_unpacked
                     (Darknet__DarknetFlows *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &darknet__darknet_flows__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor darknet__darknet_flow__field_descriptors[16] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Darknet__DarknetFlow, has_timestamp),
    offsetof(Darknet__DarknetFlow, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_bytes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Darknet__DarknetFlow, has_in_bytes),
    offsetof(Darknet__DarknetFlow, in_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_pkts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Darknet__DarknetFlow, has_in_pkts),
    offsetof(Darknet__DarknetFlow, in_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_port",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_input_port),
    offsetof(Darknet__DarknetFlow, input_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_dst_addr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_ipv4_dst_addr),
    offsetof(Darknet__DarknetFlow, ipv4_dst_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_src_addr",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_ipv4_src_addr),
    offsetof(Darknet__DarknetFlow, ipv4_src_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "l4_dst_port",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_l4_dst_port),
    offsetof(Darknet__DarknetFlow, l4_dst_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "l4_src_port",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_l4_src_port),
    offsetof(Darknet__DarknetFlow, l4_src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_port",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_output_port),
    offsetof(Darknet__DarknetFlow, output_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_protocol),
    offsetof(Darknet__DarknetFlow, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_flags",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_tcp_flags),
    offsetof(Darknet__DarknetFlow, tcp_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan_in",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_vlan_in),
    offsetof(Darknet__DarknetFlow, vlan_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan_out",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_vlan_out),
    offsetof(Darknet__DarknetFlow, vlan_out),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_sample_rate),
    offsetof(Darknet__DarknetFlow, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_id",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Darknet__DarknetFlow, has_packet_id),
    offsetof(Darknet__DarknetFlow, packet_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Darknet__DarknetFlow, has_device_id),
    offsetof(Darknet__DarknetFlow, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned darknet__darknet_flow__field_indices_by_name[] = {
  15,   /* field[15] = device_id */
  1,   /* field[1] = in_bytes */
  2,   /* field[2] = in_pkts */
  3,   /* field[3] = input_port */
  4,   /* field[4] = ipv4_dst_addr */
  5,   /* field[5] = ipv4_src_addr */
  6,   /* field[6] = l4_dst_port */
  7,   /* field[7] = l4_src_port */
  8,   /* field[8] = output_port */
  14,   /* field[14] = packet_id */
  9,   /* field[9] = protocol */
  13,   /* field[13] = sample_rate */
  10,   /* field[10] = tcp_flags */
  0,   /* field[0] = timestamp */
  11,   /* field[11] = vlan_in */
  12,   /* field[12] = vlan_out */
};
static const ProtobufCIntRange darknet__darknet_flow__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor darknet__darknet_flow__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "darknet.DarknetFlow",
  "DarknetFlow",
  "Darknet__DarknetFlow",
  "darknet",
  sizeof(Darknet__DarknetFlow),
  16,
  darknet__darknet_flow__field_descriptors,
  darknet__darknet_flow__field_indices_by_name,
  1,  darknet__darknet_flow__number_ranges,
  (ProtobufCMessageInit) darknet__darknet_flow__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor darknet__darknet_flows__field_descriptors[1] =
{
  {
    "flow",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Darknet__DarknetFlows, n_flow),
    offsetof(Darknet__DarknetFlows, flow),
    &darknet__darknet_flow__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned darknet__darknet_flows__field_indices_by_name[] = {
  0,   /* field[0] = flow */
};
static const ProtobufCIntRange darknet__darknet_flows__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor darknet__darknet_flows__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "darknet.DarknetFlows",
  "DarknetFlows",
  "Darknet__DarknetFlows",
  "darknet",
  sizeof(Darknet__DarknetFlows),
  1,
  darknet__darknet_flows__field_descriptors,
  darknet__darknet_flows__field_indices_by_name,
  1,  darknet__darknet_flows__number_ranges,
  (ProtobufCMessageInit) darknet__darknet_flows__init,
  NULL,NULL,NULL    /* reserved[123] */
};
